# Generated by Django 6.0.3 on 2026-05-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "视频"),
                            ("article", "文章"),
                            ("exercise", "练习题"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "初级"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "cover_image",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("avg_rating", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                ("browse_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学习资源",
                "verbose_name_plural": "学习资源",
                "ordering": ["-created_at"],
            },
        ),
    ]
